name: Meeles_Partner
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.5+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12
  http: any
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.2
  time_range: ^0.5.0
  image_picker: ^0.6.7+11
  firebase_storage: ^5.0.1
  intl: ^0.16.1
  toggle_switch: ^0.1.8
  font_awesome_flutter: ^8.10.0
  flutter_time_picker_spinner: ^1.0.6+1
  transparent_image: ^1.0.0
  qrscan: ^0.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/meeles.png"

flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

